---

- name: Disable SELinux
  shell: setenforce 0; sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- include: firewalld.yml

- name: configure kubernetes repositories
  template:
    src: templates/kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0440
    force: yes

- name: Ensure kubeadm packages are installed
  package:
    name: '{{ item }}'
    state: present
  become: yes
  with_items:
    - docker
    - kubeadm
    - kubelet

- name: Restart docker
  command: /bin/true
  notify: Restart docker

- name: Restart kubelet
  command: /bin/true
  notify: Restart kubelet

# - name: Start docker
#   service:
#     name: docker
#     enabled: yes
#     daemon_reload: yes
#     state: started

# - name: Restart kubelet
#   service:
#     name: kubelet
#     enabled: yes
#     daemon_reload: yes
#     state: restarted

- include: swap.yml