---

- include: prepare-system.yml
- include: init-master.yml
- include: admin-user.yml
- include: network-weave.yml
# - include: network-calico.yml
- include: join-command.yml

- name: Checking nodes
  shell: kubectl get nodes
