---

- name: Set hostname k8s-master
  shell: hostnamectl set-hostname 'k8s-master'

- name: Ensure docker, kubeadm and kubectl packages are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - kubectl

- name: make sure docker is running
  service: 
    name: docker 
    enabled: yes
    state: started

- name: make sure kubelet is running
  service: 
    name: kubelet 
    enabled: yes
    state: started