---

- name: Restart docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
